export enum ReviewsActionTypes {
    FETCH_REVIEWS_REQUEST = `FETCH_REVIEWS_REQUEST`,
    FETCH_REVIEWS_SUCCESS = `FETCH_REVIEWS_SUCCESS`,
    FETCH_REVIEWS_FAIL = `FETCH_REVIEWS_FAIL`,
    FETCH_REVIEW_REQUEST = `FETCH_REVIEW_REQUEST`,
    FETCH_REVIEW_SUCCESS = `FETCH_REVIEW_SUCCESS`,
    FETCH_REVIEW_FAIL = `FETCH_REVIEW_FAIL`,
    RESET_REVIEW_ERROR = `RESET_REVIEW_ERROR`
}
