export enum FavoritesActionTypes {
    FETCH_FAVORITES_REQUEST = `FETCH_FAVORITES_REQUEST`,
    FETCH_FAVORITES_SUCCESS = `FETCH_FAVORITES_SUCCESS`,
    FETCH_FAVORITES_FAIL = `FETCH_FAVORITES_FAIL`,
    FETCH_FAVORITE_REQUEST = `FETCH_FAVORITE_REQUEST`,
    FETCH_FAVORITE_SUCCESS = `FETCH_FAVORITE_SUCCESS`,
    FETCH_FAVORITE_FAIL = `FETCH_FAVORITE_FAIL`
}
