export enum FilmsActionTypes {
    FETCH_FILMS_REQUEST = `FETCH_FILMS_REQUEST`,
    FETCH_FILMS_SUCCESS = `FETCH_FILMS_SUCCESS`,
    FETCH_FILMS_FAIL = `FETCH_FILMS_FAIL`,
    SET_FILTER = `SET_FILTER`
}
