export enum AuthActionTypes {
    FETCH_AUTH_REQUEST = `FETCH_AUTH_REQUEST`,
    FETCH_AUTH_SUCCESS = `FETCH_AUTH_SUCCESS`,
    FETCH_AUTH_FAIL = `FETCH_AUTH_FAIL`,
    FETCH_AUTH_STATUS_REQUEST = `FETCH_AUTH_STATUS_REQUEST`,
    FETCH_AUTH_STATUS_SUCCESS = `FETCH_AUTH_STATUS_SUCCESS`,
    FETCH_AUTH_STATUS_FAIL = `FETCH_AUTH_STATUS_FAIL`,
    AUTH_STATUS_UNAUTHORIZED = `AUTH_STATUS_UNAUTHORIZED`
}
